version: '3'
services:
  api:
    container_name: api
    image: $ApiImageTag 
    ports:
      - '8080:8080'
    networks:
      - api-network
    environment:
      - API_PORT=8080
networks:
  api-network:
      driver: bridge