version: '3'
services:
  larry-identity-api:
    container_name: larry-identity-api
    image: $ApiImageTag
    command: ["npx","nyc","node", "./index.js"]
    volumes: 
      - ./../../../.nyc_output:/usr/src/app/.nyc_output
    ports:
      - '8080:8080'
    networks:
      - api-network
    environment:
      - API_URI=${API_URI}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - JWKS_URI=${JWKS_URI}
      - ISSUER=${ISSUER}
      - AUDIENCE=${AUDIENCE}
networks:
  api-network:
      driver: bridge